#!/bin/bash
# semantic-links: [[ゲート品質統合フレームワーク]]
# gate_gunshi_startup.sh — 軍師セッション起動時の全チェックを一括実行
# 目的: /clear後の状態復元に必要な6項目を一括チェック（知性の外部化原則）
# Usage: bash scripts/gates/gate_gunshi_startup.sh
# 参考: gate_karo_startup.sh（構造踏襲）

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
AUTO_IDLE_ACTIONS_FILE="$SCRIPT_DIR/queue/auto_idle_actions.txt"

overall="OK"
alerts=()
idle_actions=()
STARTUP_ALERT_HISTORY="$SCRIPT_DIR/logs/gunshi_startup_alert_history.tsv"
STARTUP_WARN_STREAK_THRESHOLD="${STARTUP_WARN_STREAK_THRESHOLD:-3}"

add_idle_action() {
    local action="$1"
    local existing
    for existing in "${idle_actions[@]}"; do
        [ "$existing" = "$action" ] && return 0
    done
    idle_actions+=("$action")
}

idle_action_for_alert() {
    local alert="$1"
    case "$alert" in
        *有効率*|*useful*) add_idle_action "idle Step 1: 低useful教訓のwhen/how精密化を実施" ;;
        *CS観点*|*冷え*) add_idle_action "idle Step 4: 冷え観点の遡及適用を実施" ;;
        *掲示板*) add_idle_action "掲示板を読み、自分への問いに回答" ;;
        *GP*|*proposed*) add_idle_action "idle Step 6: proposed GP即実行" ;;
        *GATE未確認*) add_idle_action "/gate-sync で未反映GATE結果を同期" ;;
        *教訓耐久率*) add_idle_action "idle Step 3: 未自動化教訓のgate化を実施" ;;
        *分析結果永続化*) add_idle_action "idle Step 5: 分析結果をdocs/researchへ永続化" ;;
        *セマンティクスインデックス*) add_idle_action "idle Step 5: セマンティクスインデックス鮮度の原因分析と更新提案" ;;
        *observations*) add_idle_action "idle Step 2: 直近draft/reportレビューへobservationsを追記" ;;
        *スキル推薦精度*) add_idle_action "idle Step 5: スキル推薦の誤差原因を分析しaliases補完案を作成" ;;
        *missed_sg*) add_idle_action "idle Step 2: missed_sg頻出観点をレビュー基準へ還流" ;;
    esac
}

write_auto_idle_actions() {
    mkdir -p "$(dirname "$AUTO_IDLE_ACTIONS_FILE")"
    if [ "${#idle_actions[@]}" -eq 0 ]; then
        rm -f "$AUTO_IDLE_ACTIONS_FILE"
        return 0
    fi
    {
        echo "# auto-generated by gate_gunshi_startup.sh"
        echo "# WARN/ALERT検出時の最優先idle自走ステップ。session_start_inject.shがpromptへ注入する。"
        local i=1
        local action
        for action in "${idle_actions[@]}"; do
            printf '%d. %s\n' "$i" "$action"
            i=$((i + 1))
        done
    } > "$AUTO_IDLE_ACTIONS_FILE"
}

# === 並列実行最適化: 遅いサブゲートを事前にバックグラウンド起動 ===
_TMP_D=$(mktemp -d)
trap 'rm -rf "$_TMP_D"' EXIT

_SKILL_REC_SH="$SCRIPT_DIR/scripts/skill_recommend_metrics.sh"
_LESSON_SH="$SCRIPT_DIR/scripts/gates/gate_lesson_health.sh"
_CS_SH="$SCRIPT_DIR/scripts/gates/gate_gunshi_cs_checklist.sh"
_OBS_SH="$SCRIPT_DIR/scripts/gates/gate_gunshi_observations.sh"
_THREE_SH="$SCRIPT_DIR/scripts/gates/gate_three_layer_health.sh"

{ set +e; if [ -f "$_SKILL_REC_SH" ]; then bash "$_SKILL_REC_SH" 30 > "$_TMP_D/skill_rec" 2>&1; echo $? > "$_TMP_D/skill_exit"; else printf '' > "$_TMP_D/skill_rec"; echo 127 > "$_TMP_D/skill_exit"; fi; } &
_PID_SKILL=$!
{ set +e; LESSON_EFFECT_NTFY_ENABLED=0 bash "$_LESSON_SH" infra > "$_TMP_D/lesson" 2>&1; echo $? > "$_TMP_D/lesson_exit"; } &
_PID_LESSON=$!
{ set +e; if [ -f "$_CS_SH" ]; then bash "$_CS_SH" > "$_TMP_D/cs" 2>&1; echo $? > "$_TMP_D/cs_exit"; else printf '' > "$_TMP_D/cs"; echo 127 > "$_TMP_D/cs_exit"; fi; } &
_PID_CS=$!
{ set +e; if [ -f "$_OBS_SH" ]; then bash "$_OBS_SH" > "$_TMP_D/obs" 2>&1; echo $? > "$_TMP_D/obs_exit"; else printf '' > "$_TMP_D/obs"; echo 127 > "$_TMP_D/obs_exit"; fi; } &
_PID_OBS=$!
{ set +e; if [ -x "$_THREE_SH" ]; then bash "$_THREE_SH" > "$_TMP_D/three" 2>&1; echo $? > "$_TMP_D/three_exit"; else printf '  WARN: gate_three_layer_health.sh不在\n' > "$_TMP_D/three"; echo 127 > "$_TMP_D/three_exit"; fi; } &
_PID_THREE=$!
find "$SCRIPT_DIR/docs/research" -maxdepth 1 -name "gunshi_*" -mmin -1440 -type f > "$_TMP_D/find_designs" 2>/dev/null &
_PID_FIND_D=$!
find "$SCRIPT_DIR/docs/research" -maxdepth 1 -name "*.md" -mtime -7 -type f > "$_TMP_D/find_research" 2>/dev/null &
_PID_FIND_R=$!
# §3.2: lord_conversation解析を並列化(python3起動~650ms削減)
{ python3 - "$SCRIPT_DIR/queue/lord_conversation.jsonl" <<'PY_LC' > "$_TMP_D/prev_session" 2>/dev/null
import sys, json
log_file = sys.argv[1]
summary = "(前セッション要約なし)"
try:
    with open(log_file, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                if entry.get("direction") == "session_summary":
                    s = entry.get("summary", "").strip()
                    if s:
                        summary = s
            except (json.JSONDecodeError, Exception):
                continue
except (FileNotFoundError, OSError):
    pass
print(summary)
PY_LC
} &
_PID_PREV_SESSION=$!
# §3.2: 掲示板チェックも並列化(python3+yaml.safe_load ~650ms)
{ python3 - "$SCRIPT_DIR/queue/bulletin_board.yaml" gunshi <<'PY_BLT' > "$_TMP_D/bulletin" 2>/dev/null
import sys, yaml
path, agent = sys.argv[1:3]
try:
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
except Exception:
    print("0"); raise SystemExit(0)
entries = data.get("entries") or []
pending = []
for entry in entries:
    if not isinstance(entry, dict):
        continue
    rc = entry.get("requires_confirmation", False)
    if not rc:
        continue
    if isinstance(rc, list) and agent not in rc:
        continue
    if str(entry.get("status", "")).lower() == "closed":
        continue
    confirmed = entry.get("confirmed_by") or []
    if agent in confirmed:
        continue
    text = str(entry.get("content", "")).splitlines()
    head = text[0] if text else ""
    pending.append(f"{entry.get('id', '?')} by {entry.get('posted_by', '?')} — {head[:60]}")
print(len(pending))
for item in pending[:3]:
    print(item)
PY_BLT
} &
_PID_BULLETIN=$!

echo "=== 軍師起動チェック $(date '+%H:%M:%S') ==="
echo ""

# --- Check 1: deepdive必読ファイル存在確認 + 強制表示 ---
echo "■ deepdive必読ファイル"
REQUIRED_READ="$SCRIPT_DIR/memory/deepdive_why_chain_20260321.md"
if [ -f "$REQUIRED_READ" ]; then
    echo "  OK: $(basename "$REQUIRED_READ") 存在確認"
else
    overall="ALERT"
    alerts+=("必読ファイル不在: memory/deepdive_why_chain_20260321.md")
    echo "  ALERT: $REQUIRED_READ が存在しない"
fi
echo ""

# Phase逐次読込ガイド（全文一括禁止 — 2026-04-15殿指示）
echo "  ■ Phase逐次読込ガイド（全文一括Read禁止。1 Phaseずつ読み、自問してから次へ）"
if [ -f "$REQUIRED_READ" ]; then
    echo "  $(basename "$REQUIRED_READ"):"
    # §3.2: python3→awk置換(python3起動~650ms削減)
    awk '
    /^## Phase/ { titles[NR] = substr($0, 4); starts[++n] = NR }
    END {
        total = NR
        if (n > 0) printf "    前文: Read(offset=1, limit=%d)\n", starts[1]-2
        for (i = 1; i <= n; i++) {
            e = (i < n) ? starts[i+1]-1 : total
            printf "    %s: Read(offset=%d, limit=%d)\n", titles[starts[i]], starts[i], e-starts[i]+1
        }
    }' "$REQUIRED_READ"
fi
echo "  ★ 全Phase必読（スキップ禁止）。1 Phaseずつ Read(offset, limit) で読め。各Phase後に1行自問。全文一括禁止。"
echo ""

# --- Check 1.5: 追体験検証Q4 (前セッション出来事注入) ---
# §3.2: 並列化済み(L86付近)。結果をtmpから読出し
wait "$_PID_PREV_SESSION" 2>/dev/null || true
_prev_session_summary="$(cat "$_TMP_D/prev_session" 2>/dev/null)" || _prev_session_summary="(取得失敗)"
[ -z "$_prev_session_summary" ] && _prev_session_summary="(前セッション要約なし)"
echo "■ 追体験検証Q4（CLAUDE.md Step 2.9 — 省略厳禁）"
echo "  Q4: deepdiveのPhase NがPhase Mで覆された例を1つ挙げよ。なぜ覆されたか？（時系列×因果）"
echo "  [前セッション出来事] ${_prev_session_summary}"
echo "  ※ Q4は前セッションの出来事を手がかりに因果をたどれ。暗記したPhase例を貼るな。"
echo ""

# --- Check 1.7: 前セッション殿裁定の三層記憶確認 ---
# 真因: /clear後に三層記憶で前セッションの因果文脈を確認しなかった(2026-06-07事故)
# 根源: Codex rate limit→CLI切替→settings.yaml未更新→GPTに戻った因果を見逃した
echo "■ 前セッション殿裁定（三層記憶）"
_lord_rulings=$(sqlite3 "$SCRIPT_DIR/data/multi_agent_shogun_memory.db" \
  "SELECT ts || ' | ' || substr(summary, 1, 120) FROM events WHERE agent = 'lord' AND direction = 'inbound' AND target = 'gunshi' AND ts >= datetime('now', '-6 hours') ORDER BY ts DESC LIMIT 5;" 2>/dev/null) || _lord_rulings=""
if [ -n "$_lord_rulings" ]; then
    echo "  直近6h殿→軍師（時系列で因果をたどれ）:"
    echo "$_lord_rulings" | while IFS= read -r line; do
        echo "    $line"
    done
else
    echo "  (直近6hの殿→軍師対話なし)"
fi
echo "  ★ 二次情報(settings.yaml/snapshot)で判断停止するな。三層記憶で因果をたどれ"
echo ""

# --- Check 2: inbox未読件数 ---
echo "■ inbox未読"
inbox_file="$SCRIPT_DIR/queue/inbox/gunshi.yaml"
if [ -f "$inbox_file" ]; then
    unread=$(grep -c 'read: false' "$inbox_file" 2>/dev/null) || unread=0
    echo "  未読: ${unread}件"
    if [ "$unread" -gt 0 ]; then
        echo "  → 未読メッセージあり。処理せよ"
    fi
else
    echo "  未読: 0件 (inbox不在)"
    unread=0
fi

# --- Check 2.5: 掲示板未確認 ---
echo "■ 掲示板未確認"
bulletin_file="$SCRIPT_DIR/queue/bulletin_board.yaml"
if [ -f "$bulletin_file" ]; then
    # §3.2: 並列化済み。結果をtmpから読出し
    wait "$_PID_BULLETIN" 2>/dev/null || true
    bulletin_result="$(cat "$_TMP_D/bulletin" 2>/dev/null)" || bulletin_result="0"
    bulletin_count=$(printf '%s\n' "$bulletin_result" | head -1)
    if [ "${bulletin_count:-0}" -gt 0 ]; then
        echo "  WARN: 未確認掲示板 ${bulletin_count}件"
        printf '%s\n' "$bulletin_result" | tail -n +2 | sed 's/^/    /'
        if [ "$overall" != "ALERT" ]; then
            overall="WARN"
            alerts+=("掲示板未確認: ${bulletin_count}件")
        fi
    else
        echo "  未確認: 0件"
    fi
else
    echo "  掲示板なし"
fi

# --- Check 3: レビューログ統計 ---
echo "■ スキル推薦 precision/recall"
wait "$_PID_SKILL" 2>/dev/null || true
_skill_rec_status=$(cat "$_TMP_D/skill_exit" 2>/dev/null || echo 1)
if [ "$_skill_rec_status" -eq 127 ]; then
    echo "  SKIP: skill_recommend_metrics.sh 不在"
else
    _skill_rec_out=$(cat "$_TMP_D/skill_rec" 2>/dev/null)
    printf '%s\n' "$_skill_rec_out" | sed 's/^/  /'
    if [ "$_skill_rec_status" -eq 2 ] && [ "$overall" != "ALERT" ]; then
        overall="WARN"
        alerts+=("スキル推薦精度: Phase 3 cmd起票候補 — 推薦抑制/aliases補完")
    elif [ "$_skill_rec_status" -ne 0 ]; then
        overall="ALERT"
        alerts+=("スキル推薦精度: 集計失敗")
    fi
fi
echo ""

echo "■ レビューログ統計"
REVIEW_LOG="$SCRIPT_DIR/logs/gunshi_review_log.yaml"
STATS_FILE="$SCRIPT_DIR/logs/gunshi_stats.yaml"
GP_TRACKER="$SCRIPT_DIR/logs/gunshi_gp_tracker.yaml"
if [ -f "$STATS_FILE" ]; then
    # 統計をgunshi_stats.yamlから抽出
    log_stats=$(awk '
    /^# 累計:/ { sub(/^# /, ""); cum=$0 }
    /^# accuracy公式:/ { sub(/^# /, ""); acc=$0 }
    /^# verdict分布:/ { sub(/^# /, ""); vd=$0 }
    /^# workaround率推移:/ { sub(/^# /, ""); wt=$0 }
    END { printf "%s|%s|%s|%s", cum, acc, vd, wt }
    ' "$STATS_FILE" 2>/dev/null || echo "|||")
    IFS='|' read -r LOG_CUMUL LOG_ACC LOG_VERDICT LOG_WA_TREND <<< "$log_stats"
    [ -n "$LOG_CUMUL" ] && echo "  $LOG_CUMUL"
    [ -n "$LOG_ACC" ] && echo "  $LOG_ACC"
    [ -n "$LOG_VERDICT" ] && echo "  $LOG_VERDICT"
    [ -n "$LOG_WA_TREND" ] && echo "  $LOG_WA_TREND"
else
    echo "  ALERT: gunshi_stats.yaml不在"
    overall="ALERT"
    alerts+=("統計ファイル不在")
fi

echo "■ 観点別集計（Adaptive gating）"
if [ -f "$REVIEW_LOG" ]; then
    # §3.2: category_stats python3を並列化(~650ms削減)
    python3 - "$REVIEW_LOG" <<'PY' > "$_TMP_D/category_stats" 2>/dev/null &
    _PID_CAT_STATS=$!
import re
import sys

path = sys.argv[1]
catalog = [
    ("assumptions", 10, [r"assumption", r"前提"]),
    ("numbers", 10, [r"number", r"数値", r"再計算", r"分母", r"分子"]),
    ("simulation", 10, [r"simulation", r"時系列", r"依存", r"並列", r"衝突"]),
    ("premortem", 10, [r"premortem", r"失敗", r"failure", r"リスク", r"silent fallback"]),
    ("north_star", 10, [r"north.?star", r"複利", r"品質向上", r"消火"]),
    ("ambiguity", 10, [r"ambiguity", r"曖昧", r"不明瞭"]),
    ("adversarial", 10, [r"adversarial", r"red.?team", r"chaos", r"攻撃"]),
]

entries = []
current = None
capture_field = None
capture_items = None

def flush():
    global current
    if current:
        entries.append(current)
    current = None

with open(path, encoding="utf-8") as fh:
    for raw in fh:
        line = raw.rstrip("\n")
        if re.match(r"^- (cmd_id|id):", line):
            flush()
            current = {"review_type": "", "verdict": "", "finding_categories": [], "text": []}
            capture_field = None
            capture_items = None
        if current is None:
            continue
        current["text"].append(line)
        if re.match(r"^\s{2}review_type:\s*", line):
            current["review_type"] = re.sub(r"^\s{2}review_type:\s*", "", line).strip().strip('"\'')
            capture_field = None
            continue
        if re.match(r"^\s{2}verdict:\s*", line):
            current["verdict"] = re.sub(r"^\s{2}verdict:\s*", "", line).strip().strip('"\'')
            capture_field = None
            continue
        if re.match(r"^\s{2}finding_categories:\s*\[", line):
            values = re.sub(r"^\s{2}finding_categories:\s*\[|\]\s*$", "", line).strip()
            if values:
                current["finding_categories"].extend([v.strip().strip('"\'') for v in values.split(",") if v.strip()])
            capture_field = None
            continue
        if re.match(r"^\s{2}finding_categories:\s*$", line):
            capture_field = "finding_categories"
            continue
        if capture_field == "finding_categories":
            if re.match(r"^\s{4}-\s*", line):
                current["finding_categories"].append(re.sub(r"^\s{4}-\s*", "", line).strip().strip('"\''))
                continue
            capture_field = None

flush()

reviews = [e for e in entries if e["review_type"] in ("draft", "report")]

def is_training(entry):
    for line in entry["text"]:
        m = re.match(r"^- (?:cmd_id|id):\s*(.+)", line)
        if m:
            return m.group(1).strip().strip("'\"").startswith("cmd_training")
    return False

prod_reviews = [e for e in reviews if not is_training(e)]
prod_window = prod_reviews[-10:] if prod_reviews else []
all_window = reviews[-10:]

# Primary: production-only window (accurate cold detection)
for name, threshold, patterns in catalog:
    hits = 0
    zero_streak = 0
    for entry in prod_window:
        categories = {c.lower() for c in entry["finding_categories"]}
        haystack = "\n".join(entry["text"]).lower()
        matched = name in categories or any(re.search(p, haystack) for p in patterns)
        if matched:
            hits += 1
            zero_streak = 0
        else:
            zero_streak += 1
    print(f"{name}|{hits}|{len(prod_window)}|{zero_streak}|{threshold}")

# Secondary: all (including training) for reference
for name, threshold, patterns in catalog:
    hits = 0
    for entry in all_window:
        categories = {c.lower() for c in entry["finding_categories"]}
        haystack = "\n".join(entry["text"]).lower()
        if name in categories or any(re.search(p, haystack) for p in patterns):
            hits += 1
    print(f"ALL_{name}|{hits}|{len(all_window)}")
PY
    wait "$_PID_CAT_STATS" 2>/dev/null || true
    category_stats="$(cat "$_TMP_D/category_stats" 2>/dev/null)"
    while IFS='|' read -r cat_name cat_hits cat_total cat_zero cat_threshold; do
        [ -n "$cat_name" ] || continue
        # ALL_ prefix = reference line (training+production combined)
        if [[ "$cat_name" == ALL_* ]]; then
            echo "  (参考:全cmd含む) ${cat_name#ALL_}: ${cat_hits}/${cat_total}件"
            continue
        fi
        echo "  ${cat_name}: ${cat_hits}/${cat_total}件(本番), zero_streak=${cat_zero}/${cat_threshold}"
        if [ "${cat_total:-0}" -gt 0 ] && [ "${cat_zero:-0}" -ge "${cat_threshold:-0}" ]; then
            echo "    LOW confidence候補: ${cat_name}観点が直近${cat_threshold}件で連続0件"
        fi
    done <<< "$category_stats"
else
    echo "  SKIP: gunshi_review_log.yaml不在"
fi

# 未処理GP(提案)件数
if [ -f "$GP_TRACKER" ]; then
    pending_gp=$(grep -c '^# |.*| pending' "$GP_TRACKER" 2>/dev/null) || pending_gp=0
    if [ "$pending_gp" -gt 0 ]; then
        echo "  未処理GP: ${pending_gp}件"
    fi
fi

# --- Check 4: karo_workarounds傾向（軍師の成績表） ---
echo "■ karo_workarounds傾向（成績表）"
wa_file="$SCRIPT_DIR/logs/karo_workarounds.yaml"
if [ -f "$wa_file" ]; then
    wa_result=$(awk '
    /^- (cmd_id|cmd|timestamp):/ {
        n++; wa[n]=0; cat[n]="uncategorized"; rc[n]=""
    }
    /^  workaround:/ {
        v=$2; if (v ~ /true|yes/) wa[n]=1
    }
    /^  category:/ {
        sub(/^  category: */, ""); gsub(/["'"'"']/, ""); cat[n]=$0
    }
    /^  root_cause:/ {
        sub(/^  root_cause: */, ""); gsub(/["'"'"']/, ""); rc[n]=substr($0,1,60)
    }
    END {
        s = (n > 5) ? n-4 : 1; total = n - s + 1
        wc=0; cat_str=""; cause_str=""
        for (i=s; i<=n; i++) {
            if (wa[i]) {
                wc++
                cats[cat[i]]++
                if (rc[i] != "") cause_str = cause_str (cause_str != "" ? " / " : "") rc[i]
            }
        }
        for (c in cats) cat_str = cat_str (cat_str != "" ? ", " : "") c ":" cats[c]
        if (cat_str == "") cat_str = "none"
        if (cause_str == "") cause_str = "none"
        printf "%d|%d|%s|%s\n", wc, total, cat_str, cause_str
    }
    ' "$wa_file" 2>/dev/null || echo "0|0|error|awk error")
    IFS='|' read -r WA_COUNT WA_TOTAL WA_CATS WA_CAUSES <<< "$wa_result"
    echo "  直近${WA_TOTAL}件: workaround=${WA_COUNT}件"
    if [ "$WA_COUNT" -gt 0 ]; then
        echo "  カテゴリ: ${WA_CATS}"
        echo "  原因: ${WA_CAUSES}"
        echo "  → Step 0 Workaround Pattern Checkで重点確認せよ"
    fi
else
    echo "  karo_workarounds.yaml不在"
fi

# --- Check 4.6: 教訓注入参照率（lesson_impact.tsv） ---
li_file="$SCRIPT_DIR/logs/lesson_impact.tsv"
if [ -f "$li_file" ] && [ "$(wc -l < "$li_file")" -gt 1 ]; then
    echo "■ 教訓注入参照率"
    # gate_lesson_health.shを正本にする。直近窓・active/deprecated除外・閾値を二重実装しない。
    wait "$_PID_LESSON" 2>/dev/null || true
    _lesson_gate_output=$(cat "$_TMP_D/lesson" 2>/dev/null || true)
    _lesson_metric=$(printf '%s\n' "$_lesson_gate_output" | awk '/^METRIC: lesson_effectiveness_threshold /{line=$0} END{print line}')
    if [ -n "$_lesson_metric" ]; then
        printf '%s\n' "$_lesson_metric" | awk '
        {
            for (i = 1; i <= NF; i++) {
                split($i, kv, "=")
                metric[kv[1]] = kv[2]
            }
            printf "  直近%scmd: 注入%s件, 参照%s件, 参照率%s\n", metric["window_cmds"], metric["injected"], metric["referenced"], metric["rate"]
            printf "  直近有効率%s (%s/%s件)。LG027: referenced率≠useful率\n", metric["useful_rate"], metric["useful"], metric["total_feedback"]
            if (metric["status"] == "ALERT") {
                printf "  ★ALERT: gate_lesson_health.sh判定。注入教訓の品質改善/淘汰を実行せよ\n"
            } else if (metric["status"] == "WARN") {
                printf "  ★WARN: gate_lesson_health.sh判定。注入教訓の品質改善を検討せよ\n"
            } else {
                printf "  OK: gate_lesson_health.sh判定=%s\n", metric["status"]
            }
        }'
    else
        echo "  SKIP: gate_lesson_health.sh metric取得失敗"
    fi
fi

# --- Check 4.5: missed_sg傾向（見逃したSG観点の蓄積） ---
echo "■ missed_sg Top3"
if [ -f "$wa_file" ]; then
    missed_sg_lines=$(awk '
    function flush_entry() {
        if (entry_started && is_wa && missed_sg != "") counts[missed_sg]++
    }
    /^- (cmd_id|cmd|timestamp|category):/ {
        flush_entry()
        entry_started=1
        is_wa=0
        missed_sg=""
        next
    }
    /^  workaround:/ {
        v=$2
        if (v ~ /true|yes/) is_wa=1
        next
    }
    /^  missed_sg:/ {
        v=$0
        sub(/^  missed_sg: */, "", v)
        gsub(/["'"'"' ]/, "", v)
        if (v != "" && v != "null" && v != "none") missed_sg=v
        next
    }
    END {
        flush_entry()
        for (sg in counts) print counts[sg] "|" sg
    }
    ' "$wa_file" 2>/dev/null | sort -t'|' -k1,1nr -k2,2 | head -3)
    if [ -n "$missed_sg_lines" ]; then
        while IFS='|' read -r sg_count sg_name; do
            [ -n "$sg_name" ] || continue
            echo "  ${sg_name}: ${sg_count}件"
            if [ "$sg_count" -ge 3 ]; then
                echo "  ALERT: missed_sg ${sg_name} が${sg_count}件蓄積。軍師レビュー観点の構造改善を急げ"
                overall="ALERT"
                alerts+=("missed_sg ${sg_name} が${sg_count}件")
            fi
        done <<< "$missed_sg_lines"
    else
        echo "  missed_sg記録なし"
    fi
else
    echo "  karo_workarounds.yaml不在"
fi

# --- Check 5: lessons_gunshi.yaml存在確認 ---
echo "■ レビュー教訓"
lessons_file="$SCRIPT_DIR/projects/infra/lessons_gunshi.yaml"
if [ -f "$lessons_file" ]; then
    lesson_count=$(grep -c '^- id: ' "$lessons_file" 2>/dev/null) || lesson_count=0
    echo "  OK: lessons_gunshi.yaml (${lesson_count}件)"
else
    echo "  WARN: lessons_gunshi.yaml不在"
    if [ "$overall" != "ALERT" ]; then
        overall="WARN"
        alerts+=("レビュー教訓不在")
    fi
fi

# --- Check 6: 直近レビュー(未GATE確認)件数 ---
echo "■ GATE未確認レビュー"
if [ -f "$REVIEW_LOG" ]; then
    ungated=$(awk '
    /^- (cmd_id|id):/ {
        if (n > 0 && !has_gate && (rt == "draft" || rt == "report")) count++
        n++; has_gate=0; rt=""
    }
    /^  gate_result:/ {
        v=$0; sub(/^  gate_result: */, "", v); gsub(/["'"'"' ]/, "", v)
        if (v != "" && v != "null" && v != "pending") has_gate=1
    }
    /^  (review_type|type):/ {
        v=$0; sub(/^  (review_type|type): */, "", v); gsub(/["'"'"']/, "", v)
        if (v == "draft" || v == "report") rt=v
    }
    END {
        if (n > 0 && !has_gate && (rt == "draft" || rt == "report")) count++
        print count+0
    }
    ' "$REVIEW_LOG" 2>/dev/null || echo "0")
    if [ "$ungated" -gt 0 ]; then
        ungated_ids=$(awk '
        function flush() {
            if (n > 0 && !has_gate && (rt == "draft" || rt == "report") && id != "") print id
            has_gate=0; rt=""; id=""
        }
        /^- (cmd_id|id):/ {
            flush(); n++
            id=$0; sub(/^- (cmd_id|id): */, "", id); gsub(/["'"'"' ]/, "", id)
        }
        /^  gate_result:/ {
            v=$0; sub(/^  gate_result: */, "", v); gsub(/["'"'"' ]/, "", v)
            if (v != "" && v != "null" && v != "pending") has_gate=1
        }
        /^  (review_type|type):/ {
            v=$0; sub(/^  (review_type|type): */, "", v); gsub(/["'"'"']/, "", v)
            if (v == "draft" || v == "report") rt=v
        }
        END { flush() }
        ' "$REVIEW_LOG" 2>/dev/null)
        # 自動sync実行（gate_result: null/不在をinboxから検知した時だけarchive全走査）
        GATE_SYNC="$SCRIPT_DIR/scripts/gunshi_gate_sync.sh"
        if [ -f "$GATE_SYNC" ]; then
            inbox_file="$SCRIPT_DIR/queue/inbox/gunshi.yaml"
            has_new_gate_result=0
            if [ -f "$inbox_file" ]; then
                has_new_gate_result=$(UNGATED_IDS="$ungated_ids" awk '
                BEGIN {
                    n=split(ENVIRON["UNGATED_IDS"], ids, "\n")
                    for (i=1; i<=n; i++) if (ids[i] != "") target[ids[i]]=1
                }
                function flush() {
                    if (read_false && has_gate && content != "") {
                        for (id in target) {
                            if (index(content, id) > 0) found=1
                        }
                    }
                    read_false=0; has_gate=0; content=""
                }
                /^[[:space:]]*-/ { flush() }
                /read:[[:space:]]*false/ { read_false=1 }
                /(content|body):/ { content=$0 }
                /gate_result:[[:space:]]*["'\'' ]*(CLEAR|BLOCK)/ { has_gate=1 }
                /type:[[:space:]]*["'\'' ]*(gate_result|gate_clear|review_feedback)/ { has_gate=1 }
                END { flush(); print found ? 1 : 0 }
                ' "$inbox_file" 2>/dev/null || echo 0)
            fi
            if [ "${GUNSHI_STARTUP_FORCE_GATE_SYNC:-0}" = "1" ] || [ "$has_new_gate_result" -eq 1 ]; then
                sync_out=$(bash "$GATE_SYNC" 2>&1) || true
                echo "  自動sync実行: $sync_out"
                # sync後に再計測
                ungated_after=$(awk '
                /^- (cmd_id|id):/ {
                    if (n > 0 && !has_gate && (rt == "draft" || rt == "report")) count++
                    n++; has_gate=0; rt=""
                }
                /^  gate_result:/ {
                    v=$0; sub(/^  gate_result: */, "", v); gsub(/["'"'"' ]/, "", v)
                    if (v != "" && v != "null" && v != "pending") has_gate=1
                }
                /^  (review_type|type):/ {
                    v=$0; sub(/^  (review_type|type): */, "", v); gsub(/["'"'"']/, "", v)
                    if (v == "draft" || v == "report") rt=v
                }
                END {
                    if (n > 0 && !has_gate && (rt == "draft" || rt == "report")) count++
                    print count+0
                }
                ' "$REVIEW_LOG" 2>/dev/null || echo "0")
            else
                sync_out="SKIP: inbox内に未反映cmdのgate_resultなし（archive全走査省略）"
                echo "  自動sync実行: $sync_out"
                ungated_after="$ungated"
            fi
            echo "  GATE結果未反映: ${ungated}→${ungated_after}件 (sync後)"
        else
            echo "  GATE結果未反映: ${ungated}件"
            echo "  → scripts/gunshi_gate_sync.sh が不在。手動更新せよ"
        fi
    else
        echo "  GATE結果未反映: 0件"
    fi
else
    echo "  SKIP: レビューログ不在"
fi

# --- Check 7: CS観点チェックリスト(consultation/self_study品質保証) ---
echo "■ CS観点チェックリスト"
wait "$_PID_CS" 2>/dev/null || true
cs_exit=$(cat "$_TMP_D/cs_exit" 2>/dev/null || echo 0)
cs_result=$(cat "$_TMP_D/cs" 2>/dev/null)
if [ "$cs_exit" -eq 127 ]; then
    echo "  SKIP: gate_gunshi_cs_checklist.sh不在"
else
    cs_relevant_warn=$(printf '%s\n' "$cs_result" | grep -m1 -E '^(WARN|ALERT).*([cC][sS]_checklist|causal_chain|operational_simulation|冷え観点|finding_categories)' || true)
    cs_summary="$cs_relevant_warn"
    [ -n "$cs_summary" ] || cs_summary=$(printf '%s\n' "$cs_result" | grep -m1 '^PASS:' || true)
    [ -n "$cs_summary" ] || cs_summary=$(printf '%s\n' "$cs_result" | head -1)
    echo "  $cs_summary"
    if [ "$cs_exit" -ne 0 ] && [ -n "$cs_relevant_warn" ]; then
        if [ "$overall" != "ALERT" ]; then
            overall="WARN"
        fi
        alerts+=("CS観点チェックリスト/冷え観点WARNあり")
        echo "  → consultation/self_study品質または冷え観点のfinding_categories反映を確認せよ"
    fi
fi

# --- Check 9: observations必須チェック(draft/reportレビュー深さ保証) ---
echo "■ observations必須チェック"
wait "$_PID_OBS" 2>/dev/null || true
_obs_exit=$(cat "$_TMP_D/obs_exit" 2>/dev/null || echo 0)
obs_result=$(cat "$_TMP_D/obs" 2>/dev/null)
if [ "$_obs_exit" -eq 127 ]; then
    echo "  SKIP: gate_gunshi_observations.sh不在"
else
    echo "  $obs_result" | head -1
    obs_exit=0  # preserve original behavior: || true makes obs_exit always 0
    if [ "$obs_exit" -ne 0 ]; then
        if [ "$overall" != "ALERT" ]; then
            overall="WARN"
        fi
        alerts+=("observations欠落あり")
        echo "  → 直近draft/reportレビューにobservationsを追記せよ"
    fi
fi

# --- セマンティクスインデックス鮮度 ---
echo "■ セマンティクスインデックス鮮度"
_si_index="$SCRIPT_DIR/docs/semantic-index/index.md"
if [ -f "$_si_index" ]; then
    _si_last_mod=$(stat -c %Y "$_si_index")
    _si_now=$(date +%s)
    _si_age_days=$(( (_si_now - _si_last_mod) / 86400 ))
    if [ "$_si_age_days" -ge 14 ]; then
        echo "  WARN: セマンティクスインデックスが${_si_age_days}日間未更新"
        if [ "$overall" != "ALERT" ]; then overall="WARN"; fi
        alerts+=("セマンティクスインデックス鮮度: ${_si_age_days}日未更新")
    else
        echo "  OK: ${_si_age_days}日前に更新"
    fi
else
    echo "  WARN: docs/semantic-index/index.md 不在"
    if [ "$overall" != "ALERT" ]; then overall="WARN"; fi
    alerts+=("セマンティクスインデックス: index不在")
fi
echo ""

# --- 教訓/clear耐久率 ---
echo "■ 教訓/clear耐久率"
_lg_file="$SCRIPT_DIR/projects/infra/lessons_gunshi.yaml"
if [ -f "$_lg_file" ]; then
    _lg_total=$(awk '/automated:/{count++} END{print count+0}' "$_lg_file" 2>/dev/null)
    _lg_auto=$(awk '/automated: true/{count++} END{print count+0}' "$_lg_file" 2>/dev/null)
    _lg_manual=$(( _lg_total - _lg_auto ))
    if [ "$_lg_total" -gt 0 ]; then
        _lg_rate=$(( _lg_auto * 100 / _lg_total ))
    else
        _lg_rate=0
    fi
    echo "  自動化: ${_lg_auto}/${_lg_total}件 (${_lg_rate}%)"
    if [ "$_lg_manual" -gt 0 ]; then
        echo "  ★ Level 2(意志依存)${_lg_manual}件 — /clear後に消える教訓:"
        # 非自動化教訓のIDとタイトルを表示
        awk '/^- id:/{id=$3} /automated: false/{print "    " id}' "$_lg_file" 2>/dev/null | head -13
        if [ "$_lg_rate" -lt 70 ]; then
            echo "  WARN: 耐久率${_lg_rate}% < 70%。idle自走Step 3でgate化を進めよ"
            if [ "$overall" != "ALERT" ]; then overall="WARN"; fi
            alerts+=("教訓耐久率: ${_lg_rate}%(${_lg_manual}件が意志依存)")
        fi
    else
        echo "  OK: 全教訓が自動化済み"
    fi
else
    echo "  SKIP: lessons_gunshi.yaml不在"
fi
echo ""

# --- 洗脳監査(行動→結果検証の二値チェック) ---
echo "■ 洗脳監査(行動→結果検証)"
echo "  8パターン: (1)早期終了 (2)検証スキップ (3)他者依存 (4)緩い設計 (5)先送り (6)出力=仕事 (7)簡潔本能[質問形の範囲縮小提案含む=LS052] (8)完了急ぎ"
_rl_file="$SCRIPT_DIR/logs/gunshi_review_log.yaml"
if [ -f "$_rl_file" ]; then
    # APPROVE verdictのgate_result確認率(行動→結果検証の計測)
    # 計測窓=直近30エントリ。全期間累積は過去エントリ(導入前)の未記入が
    # 永久WARN化し形骸化する(2026-06-10実測: self_study旧エントリ32件が
    # 解消不能CRITICALとして3セッション連続escalation。cmd_2732と同根)。
    # brainwash_checkはverdict付き(APPROVE/LGTM)レビュー限定。
    # self_studyはcs_checklist+causal_chain(gate_gunshi_cs_checklist.sh)が担当。
    _rl_window_start=$(grep -n "^- cmd_id:" "$_rl_file" | tail -30 | head -1 | cut -d: -f1)
    _rl_window_start=${_rl_window_start:-1}
    _bw_review=$(tail -n +"$_rl_window_start" "$_rl_file" | awk '
    BEGIN { approve_total=0; has_gr=0; no_gr=0; no_gr_cmds=""; has_bc=0; no_bc=0 }
    /^- cmd_id:/ { flush(); in_entry=1; verdict=""; gate_result=0; bc=0; cmd_label=$3; gsub(/["'"'"']/, "", cmd_label) }
    in_entry && /^  cmd_id:/ { sub(/.*cmd_id: */, ""); gsub(/["'"'"']/, ""); cmd_label=$0 }
    in_entry && /verdict: APPROVE/ { verdict="APPROVE" }
    in_entry && /verdict: LGTM/ { verdict="LGTM" }
    in_entry && /gate_result:/ { gate_result=1 }
    in_entry && /brainwash_check:/ { bc=1 }
    function flush() {
        if (!in_entry) return
        if (verdict == "APPROVE" || verdict == "LGTM") {
            approve_total++
            if (gate_result) has_gr++
            else {
                no_gr++
                if (no_gr <= 5) {
                    if (no_gr_cmds != "") no_gr_cmds = no_gr_cmds ", "
                    no_gr_cmds = no_gr_cmds cmd_label
                }
            }
            if (bc) has_bc++; else no_bc++
        }
        in_entry=0; verdict=""; gate_result=0; bc=0; cmd_label=""
    }
    END { flush(); print approve_total "|" has_gr "|" no_gr "|" no_gr_cmds "|" has_bc "|" no_bc }
    ')
    IFS='|' read -r _rv_total _rv_gr _rv_no_gr _rv_cmds _rv_bc _rv_no_bc <<< "$_bw_review"
    _rv_total=${_rv_total:-0}
    _rv_gr=${_rv_gr:-0}
    _rv_no_gr=${_rv_no_gr:-0}
    _rv_bc=${_rv_bc:-0}
    _rv_no_bc=${_rv_no_bc:-0}
    if [ "$_rv_total" -gt 0 ]; then
        _rv_rate=$(( _rv_gr * 100 / _rv_total ))
    else
        _rv_rate=0
    fi
    echo "  APPROVE/LGTM後のgate_result確認率: ${_rv_rate}% (${_rv_gr}/${_rv_total})"
    if [ "$_rv_no_gr" -gt 5 ]; then
        echo "  WARN: gate_result未確認 ${_rv_no_gr}件(直近5件: ${_rv_cmds})"
        echo "  → レビュー判定(行動)後にgate結果(結果検証)を閉じよ。/gate-syncを実行"
        if [ "$overall" != "ALERT" ]; then overall="WARN"; fi
        alerts+=("洗脳監査: gate_result未確認 ${_rv_no_gr}件")
    elif [ "$_rv_no_gr" -gt 0 ]; then
        echo "  INFO: gate_result未確認 ${_rv_no_gr}件: ${_rv_cmds}"
    else
        echo "  OK: 全APPROVE/LGTMにgate_result記録済み"
    fi
    echo "  brainwash_check記入: ${_rv_bc}件 / 未記入: ${_rv_no_bc}件"
    if [ "$_rv_no_bc" -gt 5 ]; then
        echo "  WARN: brainwash_check未記入 ${_rv_no_bc}件"
        if [ "$overall" != "ALERT" ]; then overall="WARN"; fi
        alerts+=("洗脳監査: brainwash_check未記入レビュー ${_rv_no_bc}件")
    fi
else
    echo "  SKIP: gunshi_review_log.yaml不在"
fi
echo "  ★ 自問: 直近のレビュー判定で「検証スキップ」「完了急ぎ」に乗っていないか？"
# L5: 前セッション洗脳発現パターン表示（次セッションで同じ罠に落ちない）
if [ -f "$REVIEW_LOG" ]; then
    _bw_patterns=$(awk '
    /brainwash_check:/ {
        gsub(/.*brainwash_check: *"?/, ""); gsub(/"$/, "")
        for (i=1; i<=8; i++) {
            p = "#" i
            if (index($0, p) > 0) count[i]++
        }
        total++
    }
    END {
        if (total > 0) {
            labels[1]="早期終了"; labels[2]="検証スキップ"; labels[3]="他者依存"
            labels[4]="緩い設計"; labels[5]="先送り"; labels[6]="出力=仕事"
            labels[7]="簡潔本能"; labels[8]="完了急ぎ"
            for (i=1; i<=8; i++) {
                if (count[i]+0 > 0) printf "#%d(%s):%d ", i, labels[i], count[i]
            }
        }
    }' "$REVIEW_LOG" 2>/dev/null)
    if [ -n "$_bw_patterns" ]; then
        echo "  前セッション洗脳発現: $_bw_patterns"
        echo "  → 同じパターンに今セッションで乗っていないか？"
    fi
fi
echo ""

# --- ストリーク検出: 3セッション連続WARN/ALERT→BLOCK昇格 (L7横展開: gate_shogun_startup.sh準拠) ---
if [ "${#alerts[@]}" -gt 0 ]; then
    mkdir -p "$(dirname "$STARTUP_ALERT_HISTORY")"
    _streak_result=$(python3 - "$STARTUP_ALERT_HISTORY" "${STARTUP_WARN_STREAK_THRESHOLD}" "${alerts[@]}" <<'PY' 2>/dev/null || true
import sys
from pathlib import Path

path = Path(sys.argv[1])
try:
    threshold = int(sys.argv[2])
except ValueError:
    threshold = 3
current = [a.strip() for a in sys.argv[3:] if a.strip()]
if not current or threshold <= 1:
    sys.exit(0)

runs = []
if path.exists():
    current_run = None
    current_keys = set()
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        parts = raw.split("\t", 1)
        if len(parts) != 2:
            continue
        run_id, key = parts
        if current_run is None:
            current_run = run_id
        if run_id != current_run:
            runs.append(current_keys)
            current_run = run_id
            current_keys = set()
        if key != "__OK__":
            current_keys.add(key)
    if current_run is not None:
        runs.append(current_keys)

previous = runs[-(threshold - 1):]
for key in current:
    if len(previous) == threshold - 1 and all(key in run for run in previous):
        print(key)
PY
)
    if [ -n "$_streak_result" ]; then
        echo "■ ★★★ CRITICAL: startup WARN/ALERT連続出現 ★★★"
        while IFS= read -r _streak_key; do
            [ -n "$_streak_key" ] || continue
            echo "  ★★★ CRITICAL: ${_streak_key} が${STARTUP_WARN_STREAK_THRESHOLD}セッション連続"
            echo "  先送り判断検出: ${STARTUP_WARN_STREAK_THRESHOLD}セッション連続で未解消。低優先/後で扱いにした穴の証拠として今ふさげ。"
            alerts+=("先送りCRITICAL: ${_streak_key} が${STARTUP_WARN_STREAK_THRESHOLD}セッション連続")
        done <<< "$_streak_result"
        # 軍師BLOCKはレビュー全停止を招くため、BLOCK昇格せず起動は許可する
        # 代わりにntfyで殿に通知し、CRITICAL表示で注意喚起
        if [ "$overall" != "ALERT" ] && [ "$overall" != "BLOCK" ]; then overall="ALERT"; fi
        bash "$SCRIPT_DIR/scripts/ntfy.sh" "【軍師CRITICAL】先送り${STARTUP_WARN_STREAK_THRESHOLD}セッション連続検出。起動は許可するが即対処必須" 2>/dev/null || true
    fi
fi

# --- 三層記憶使用義務リマインダー(殿厳命2026-06-10: 使用しないのはバグ) ---
echo ""
echo "■ 三層記憶使用義務(L0-L7貫通)"
echo "  ★ 全行動で三層記憶を検索してから行動せよ。使用しないのはバグ"
echo "  (1) bash scripts/memory_db_query.sh \"SELECT ts,substr(summary,1,80) FROM events WHERE summary LIKE '%キーワード%' ORDER BY ts DESC LIMIT 3\""
echo "  (2) bash scripts/semantic_search.sh \"キーワード\""
echo "  (3) 回答に[MEM: memory_db ts=YYYY-MM-DD]タグで引用"
echo "  理解を出力するな。使え。contextファイル更新だけでは三層貫通ではない"

# --- 総合判定 ---
echo ""
echo "=== 総合判定: $overall ==="
if [ ${#alerts[@]} -gt 0 ]; then
    for a in "${alerts[@]}"; do
        echo "  ⚠ $a"
        idle_action_for_alert "$a"
    done
    # Bug 2 fix: 計測→行動ループ。WARN/ALERT→具体的行動を自動推薦
    echo ""
    echo "■ 推薦行動（WARN/ALERTから自動導出）"
    if [ "${#idle_actions[@]}" -gt 0 ]; then
        for action in "${idle_actions[@]}"; do
            echo "  → $action"
        done
        write_auto_idle_actions
        echo "  → auto_idle_actions.txt: $AUTO_IDLE_ACTIONS_FILE"
    else
        echo "  → 対応する自走ステップ未定義。alertsを読み、idle Step 5で原因分析"
    fi
else
    rm -f "$AUTO_IDLE_ACTIONS_FILE"
fi
echo ""
echo "■ 必読: memory/deepdive_why_chain_20260321.md（知性の外部化原則 全過程）"
echo "■ 必読: logs/gunshi_stats.yaml（accuracy把握）"
echo "■ 必読: projects/infra/lessons_gunshi.yaml（レビュー教訓）"
echo ""
echo "■ ★★★ セッション知見(2026-04-03殿指摘) ★★★"
echo "  共通根因: 「知っている」≠「使っている」"
echo "  穴1: 研究cmdでengine統合を見落とす → SG10(review_logヘッダ)で確認"
echo "  穴2: 参照ドキュメントを読んだつもり → 引用時に定義を1行で明示。書けなければ読み直せ"
echo "  穴3: チェックリスト≠gate → 新SG作成時に「読み飛ばせるか?」自問。YES→gate化提案"
echo "  穴4: LG001再発(2026-05-11) — 「既実装」判定にRead tool使用→忍者作業中変更を既存と誤判定。★git show HEAD:ファイルで確認必須★"
echo "  → 上記がlessons_gunshi.yamlに登録済みか確認せよ。未登録なら家老に催促"

# --- Check 8: idle自走プロンプト ---
echo ""
echo "■ 自走チェック"
if [ "$unread" -eq 0 ]; then
    echo "  inbox未読=0。レビュー依頼なし。"
    echo "  ★★★ idle時自走プロトコルを実行せよ（instructions/gunshi.md参照） ★★★"
    echo "  Step 1: karo_workarounds直近10件分析"
    echo "  Step 2: gunshi_review_log傾向分析"
    echo "  Step 3: 未自動化教訓のgate化"
    echo "  Step 4: CS観点遡及適用"
    echo "  Step 5: パターン発見→因果推論→行動"
    echo "  Step 6: proposed GP即実行（提案は行動ではない。実装して初めて行動）"
    echo "  → 止まるな。1つ完了したら次へ"
fi

# --- Check 9: proposed/pending GP件数（自力実行催促） ---
GP_TRACKER="$SCRIPT_DIR/logs/gunshi_gp_tracker.yaml"
if [ -f "$GP_TRACKER" ]; then
    proposed_count=$(grep -c '| proposed ' "$GP_TRACKER" 2>/dev/null || true)
    proposed_count=${proposed_count:-0}
    pending_count=$(grep -c '| pending ' "$GP_TRACKER" 2>/dev/null || true)
    pending_count=${pending_count:-0}
    actionable=$((proposed_count + pending_count))
    if [ "$actionable" -gt 0 ]; then
        echo ""
        echo "■ GP未実行チェック"
        echo "  proposed: ${proposed_count}件, pending: ${pending_count}件"
        echo "  → 自力実行可能か判定せよ。可能なら即実装+テスト+完了"
        echo "  → 「家老送信=完了」は錯覚。提案は記録であり行動ではない"
        grep -E '\| proposed |\| pending ' "$GP_TRACKER" 2>/dev/null | sed 's/^#/  /' || true
    fi
fi

# --- Check 9.5: 設計書セルフレビュー催促 ---
# docs/research/gunshi_* が直近24h以内に更新されていたら、セルフレビュー3点を表示
wait "$_PID_FIND_D" 2>/dev/null || true
recent_designs=$(head -5 "$_TMP_D/find_designs" 2>/dev/null)
if [ -n "$recent_designs" ]; then
    echo ""
    echo "■ 設計書セルフレビュー"
    echo "  直近24h更新の設計書:"
    echo "$recent_designs" | while read -r f; do echo "    $(basename "$f")"; done
    echo "  ★ 保存前セルフレビュー3点を実施したか？"
    echo "    1. 数値検算: 全数値を入力データから再計算(wc -l/head実測)"
    echo "    2. 前提検証: 入力ファイル存在・フォーマット・日付範囲を現物確認"
    echo "    3. 事前検死: 忍者がどこで詰まるか。完了条件・baseline・結果の使い方"
fi

# --- Check 10: 分析結果永続化チェック(GP-165: 自動化×強制) ---
echo ""
echo "■ 分析結果永続化チェック"
# 直近のself_studyエントリにdocs/research/参照があるか確認
# + 直近7日のdocs/research/更新があるか確認
if [ -d "$SCRIPT_DIR/docs/research" ]; then
    wait "$_PID_FIND_R" 2>/dev/null || true
    recent_research=$(wc -l < "$_TMP_D/find_research" 2>/dev/null || echo 0)
    echo "  docs/research/ 直近7日更新: ${recent_research}件"
    if [ "$recent_research" -eq 0 ]; then
        echo "  WARN: 直近7日で分析結果の永続化なし"
        echo "  → 分析をinbox_writeで送るだけで終わるな。docs/research/に永続化せよ"
        echo "  → CS4: 気付きをinbox(揮発)に閉じず、永続ドキュメントに変換せよ"
        if [ "$overall" != "ALERT" ]; then
            overall="WARN"
        fi
        alerts+=("分析結果永続化なし(7日間)")
    fi
else
    echo "  SKIP: docs/research/不在"
fi

# --- Check 11: 三層学習ループ健全性計測(2026-04-18殿指摘: 環境に埋め込め) ---
# なぜなぜ7回(殿指摘): 累積FAIL数はノイズ含む。FAIL→PASS遷移=免疫が実際に発動した件数
echo ""
echo "■ 三層学習ループ健全性"
_fire_log="$SCRIPT_DIR/logs/gate_fire_log.yaml"
_wa_log="$SCRIPT_DIR/logs/karo_workarounds.yaml"
if [ -f "$_fire_log" ]; then
    # 免疫効果 = 同一ファイルでFAIL後にPASSした件数(gateが止めて忍者が自力修正)
    # §3.2: python3→awk置換(~650ms削減)
    _healed=$(awk '
        match($0, /file: "([^"]+)".*result: (FAIL|PASS)/, m) {
            if (m[2] == "FAIL") fails[m[1]] = 1
            else if (m[2] == "PASS" && m[1] in fails) healed++
        }
        END { print healed+0 }
    ' "$_fire_log" 2>/dev/null || echo 0)
    _fail_total=$(grep -c 'result: FAIL' "$_fire_log" 2>/dev/null || echo 0)
    # 現存報告のFAIL数(ノイズ除外)
    _fail_live=0
    while IFS= read -r _fl; do
        if [ -f "$_fl" ]; then (( _fail_live++ )) || true; fi
    done < <(grep 'result: FAIL' "$_fire_log" 2>/dev/null | grep -oP '/mnt/c[^"]+' | sort -u)
    echo "  第三層(免疫効果): FAIL→PASS遷移=${_healed}件(gateが止め忍者が自力修正)"
    echo "  第三層(参考): 累積FAIL=${_fail_total}件(うち現存報告=${_fail_live}件。差分=archive済み旧報告ノイズ)"
fi
if [ -f "$_wa_log" ]; then
    _wa_recent=$(tail -50 "$_wa_log" | grep -c 'workaround: true' || true)
    _clean_recent=$(tail -50 "$_wa_log" | grep -c 'workaround: false' || true)
    echo "  第二層(対): 直近WA=${_wa_recent}件 / clean=${_clean_recent}件"
fi
_lessons_count=$(awk '/^- id: LG/{count++} END{print count+0}' "$SCRIPT_DIR/projects/infra/lessons_gunshi.yaml" 2>/dev/null)
_auto_count=$(awk '/automated: true/{count++} END{print count+0}' "$SCRIPT_DIR/projects/infra/lessons_gunshi.yaml" 2>/dev/null)
echo "  第一層(個): 教訓${_lessons_count}件(automated:${_auto_count}件)"
echo "  ★ FAIL→PASS遷移が免疫の直接計測。累積FAILは旧報告ノイズ含む(なぜなぜ7回, 2026-04-18殿指摘)"

# --- Check 11.5: 三層記憶DB健全性 ---
echo ""
echo "■ 三層記憶DB健全性"
wait "$_PID_THREE" 2>/dev/null || true
_three_exit=$(cat "$_TMP_D/three_exit" 2>/dev/null || echo 0)
three_layer_health_output=$(cat "$_TMP_D/three" 2>/dev/null)
printf '%s\n' "$three_layer_health_output" | sed 's/^/  /'
if [ "$_three_exit" -ne 0 ]; then
    if [ "$overall" != "ALERT" ] && [ "$overall" != "BLOCK" ]; then overall="WARN"; fi
    if [ "$_three_exit" -eq 127 ]; then
        alerts+=("三層記憶DB健全性: gate不在")
    else
        alerts+=("三層記憶DB健全性: WARN")
    fi
fi

# --- Alert history記録 (gate_shogun_startup.sh準拠) ---
mkdir -p "$(dirname "$STARTUP_ALERT_HISTORY")"
_startup_run_id="$(date '+%Y-%m-%dT%H:%M:%S%z')"
if [ ${#alerts[@]} -gt 0 ]; then
    for a in "${alerts[@]}"; do
        printf '%s\t%s\n' "$_startup_run_id" "$a" >> "$STARTUP_ALERT_HISTORY"
    done
else
    printf '%s\t__OK__\n' "$_startup_run_id" >> "$STARTUP_ALERT_HISTORY"
fi

# --- L1先送り自動エスカレーション: 先送りCRITICAL検出→家老にinbox送信 ---
if [ ${#alerts[@]} -gt 0 ]; then
    _deferred_alerts=""
    for a in "${alerts[@]}"; do
        case "$a" in
            先送りCRITICAL:*)
                _deferred_alerts="${_deferred_alerts:+${_deferred_alerts}; }${a}"
                ;;
        esac
    done
    if [ -n "$_deferred_alerts" ]; then
        _deferred_message="軍師startup先送りCRITICAL自動エスカレーション: ${_deferred_alerts}。軍師が対処できないため家老karo_directで対処を検討せよ"
        _deferred_dup_status=$(python3 - "$SCRIPT_DIR/queue/inbox/karo.yaml" "$_deferred_message" <<'PY' 2>/dev/null || true
import sys
from pathlib import Path

try:
    import yaml
except Exception:
    raise SystemExit(0)

path = Path(sys.argv[1])
target = sys.argv[2]
if not path.exists():
    raise SystemExit(0)

try:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
except Exception:
    raise SystemExit(0)

for msg in data.get("messages") or []:
    if not isinstance(msg, dict):
        continue
    if msg.get("read"):
        continue
    if msg.get("from") == "gunshi" and msg.get("type") == "escalation" and msg.get("content") == target:
        print("duplicate_unread")
        break
PY
)
        if [ "$_deferred_dup_status" = "duplicate_unread" ]; then
            echo "  SKIP: 同一未読escalationが家老inboxに存在 — 重複送信を抑制"
        else
            bash "$SCRIPT_DIR/scripts/inbox_write.sh" karo \
                "$_deferred_message" \
                escalation gunshi 2>/dev/null || true
        fi
        unset _deferred_message _deferred_dup_status
    fi
fi
