#!/usr/bin/env python3
"""Backfill missing lesson when/how fields in lessons.md SSOT files.

The cache files under projects/*/lessons.yaml are generated by sync_lessons.sh.
This script updates the source Markdown with flock, then runs sync_lessons.sh so
the generated index receives the same fields.
"""

from __future__ import annotations

import argparse
import datetime as dt
import fcntl
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml


UNSET = {"", "未設定", "none", "null", "None", "NULL"}


@dataclass
class LessonBlock:
    lesson_id: str
    title: str
    start: int
    end: int
    has_when: bool
    has_how: bool
    insert_after: int
    text: str


def script_dir() -> Path:
    env_dir = os.environ.get("BACKFILL_LESSON_SCRIPT_DIR")
    if env_dir:
        return Path(env_dir).resolve()
    return Path(__file__).resolve().parents[1]


def load_projects(root: Path) -> dict[str, Path]:
    config = root / "config" / "projects.yaml"
    with config.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    projects: dict[str, Path] = {}
    for item in data.get("projects", []):
        if not isinstance(item, dict):
            continue
        project_id = str(item.get("id", "")).strip()
        path = str(item.get("path", "")).strip()
        if project_id and path:
            projects[project_id] = Path(path)
    return projects


def is_set(value: str | None) -> bool:
    return (value or "").strip().strip("'\"") not in UNSET


def metadata_value(lines: list[str], key: str) -> str | None:
    pat = re.compile(rf"^\s*-\s+\*\*{re.escape(key)}\*\*:\s*(.*)$")
    for line in lines:
        match = pat.match(line)
        if match:
            return match.group(1).strip()
    return None


def parse_blocks(lines: list[str]) -> list[LessonBlock]:
    heading_re = re.compile(r"^###\s+(L\d+)\s*[:：]\s*(.+?)\s*$")
    headings: list[tuple[int, str, str]] = []
    for idx, line in enumerate(lines):
        match = heading_re.match(line)
        if match:
            headings.append((idx, match.group(1), match.group(2)))

    blocks: list[LessonBlock] = []
    for pos, (start, lesson_id, title) in enumerate(headings):
        end = headings[pos + 1][0] if pos + 1 < len(headings) else len(lines)
        body = lines[start + 1 : end]
        when = metadata_value(body, "when")
        how = metadata_value(body, "how")
        insert_after = start
        for idx in range(start + 1, end):
            stripped = lines[idx].strip()
            if stripped.startswith("- **"):
                insert_after = idx
                continue
            if stripped == "":
                continue
            break
        blocks.append(
            LessonBlock(
                lesson_id=lesson_id,
                title=title,
                start=start,
                end=end,
                has_when=is_set(when),
                has_how=is_set(how),
                insert_after=insert_after,
                text="\n".join(body),
            )
        )
    return blocks


def first_field_line(lines: list[str], start: int, end: int, key: str) -> int | None:
    pat = re.compile(rf"^\s*-\s+\*\*{re.escape(key)}\*\*:\s*")
    for idx in range(start, end):
        if pat.match(lines[idx]):
            return idx
    return None


def clean_sentence(text: str) -> str:
    text = re.sub(r"^\s*-\s+", "", text.strip())
    text = re.sub(r"^\*\*[^*]+\*\*:\s*", "", text)
    text = re.sub(r"\s+", " ", text)
    text = text.strip(" 。")
    return text[:140] if text else ""


def split_sentences(text: str) -> list[str]:
    raw = re.split(r"[。\n]", text)
    return [clean_sentence(s) for s in raw if clean_sentence(s)]


def infer_from_if_then(text: str) -> tuple[str | None, str | None]:
    if_line = metadata_value(text.splitlines(), "if")
    then_line = metadata_value(text.splitlines(), "then")
    if is_set(if_line) or is_set(then_line):
        return (if_line if is_set(if_line) else None, then_line if is_set(then_line) else None)

    match = re.search(r"\bIF\s+(.+?)\s+THEN\s+(.+?)(?:\s+BECAUSE|\n|$)", text, re.IGNORECASE)
    if match:
        return clean_sentence(match.group(1)), clean_sentence(match.group(2))
    return None, None


def infer_when(block: LessonBlock) -> str:
    if_cond, _ = infer_from_if_then(block.text)
    if is_set(if_cond):
        return clean_sentence(if_cond or "")

    title = block.title
    for marker in ("時は", "時に", "場合は", "場合に", "際は", "際に", "するとき"):
        if marker in title:
            head = title.split(marker, 1)[0].strip()
            if head:
                return clean_sentence(f"{head}{marker}")

    tags = metadata_value(block.text.splitlines(), "tags") or ""
    if "gate" in tags or "ゲート" in title:
        return "gateやhookの検知・補正ロジックを変更する時"
    if "report" in tags or "報告" in title:
        return "報告YAMLやレビュー結果を作成・検証する時"
    if "deploy" in tags or "配備" in title:
        return "タスク配備やデプロイ手順を変更・実行する時"
    if "db" in tags or "DB" in title or "データ" in title:
        return "DB・データ取得・永続化に関わる作業を行う時"
    if "frontend" in tags or "FE" in title or "UI" in title:
        return "frontend/UIの表示・状態管理を変更する時"
    if "testing" in tags or "テスト" in title:
        return "テスト設計・実行・結果判定を行う時"
    return "同種の作業・判断・検証を行う時"


def infer_how(block: LessonBlock) -> str:
    _, then_action = infer_from_if_then(block.text)
    cleaned_then = clean_sentence(then_action or "") if is_set(then_action) else ""
    if cleaned_then:
        return cleaned_then

    action_keywords = (
        "必ず",
        "確認",
        "使え",
        "使用",
        "実行",
        "追加",
        "修正",
        "設定",
        "避け",
        "禁止",
        "せよ",
        "するな",
        "必要",
        "fallback",
        "同期",
        "検証",
    )
    non_meta_text = "\n".join(
        line for line in block.text.splitlines() if not re.match(r"^\s*-\s+\*\*[^*]+\*\*:", line)
    )
    sentences = split_sentences(non_meta_text)
    for sentence in sentences:
        if any(keyword in sentence for keyword in action_keywords):
            return sentence
    if sentences:
        return sentences[0]
    return clean_sentence(block.title)


def stats(blocks: list[LessonBlock]) -> tuple[int, int, int]:
    total = len(blocks)
    when_count = sum(1 for block in blocks if block.has_when)
    how_count = sum(1 for block in blocks if block.has_how)
    return total, when_count, how_count


def rate(ok: int, total: int) -> str:
    return f"{(ok / total * 100):.1f}%" if total else "100.0%"


def backfill_file(path: Path, limit: int | None, dry_run: bool) -> dict[str, int]:
    lock_path = path.with_suffix(path.suffix + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a", encoding="utf-8") as lock_fh:
        fcntl.flock(lock_fh.fileno(), fcntl.LOCK_EX)
        lines = path.read_text(encoding="utf-8").splitlines()
        blocks = parse_blocks(lines)
        total, before_when, before_how = stats(blocks)
        inserts: list[tuple[int, list[str]]] = []
        replacements: dict[int, str] = {}
        changed = 0
        for block in blocks:
            additions: list[str] = []
            block_changed = False
            if not block.has_when:
                replacement = f"- **when**: {infer_when(block)}"
                existing_idx = first_field_line(lines, block.start + 1, block.end, "when")
                if existing_idx is None:
                    additions.append(replacement)
                else:
                    replacements[existing_idx] = replacement
                block_changed = True
            if not block.has_how:
                replacement = f"- **how**: {infer_how(block)}"
                existing_idx = first_field_line(lines, block.start + 1, block.end, "how")
                if existing_idx is None:
                    additions.append(replacement)
                else:
                    replacements[existing_idx] = replacement
                block_changed = True
            if block_changed:
                inserts.append((block.insert_after + 1, additions))
                changed += 1
                if limit is not None and changed >= limit:
                    break

        if (inserts or replacements) and not dry_run:
            for idx, value in replacements.items():
                lines[idx] = value
            for insert_idx, additions in reversed(inserts):
                if not additions:
                    continue
                lines[insert_idx:insert_idx] = additions
            path.write_text("\n".join(lines) + "\n", encoding="utf-8")

        if dry_run:
            sim_lines = list(lines)
            for idx, value in replacements.items():
                sim_lines[idx] = value
            for insert_idx, additions in reversed(inserts):
                if not additions:
                    continue
                sim_lines[insert_idx:insert_idx] = additions
            after_blocks = parse_blocks(sim_lines)
            _, after_when, after_how = stats(after_blocks)
        else:
            after_blocks = parse_blocks(path.read_text(encoding="utf-8").splitlines())
            _, after_when, after_how = stats(after_blocks)

        return {
            "total": total,
            "before_when": before_when,
            "before_how": before_how,
            "after_when": after_when,
            "after_how": after_how,
            "changed_lessons": changed,
        }


def sync_project(root: Path, project_id: str) -> None:
    subprocess.run([str(root / "scripts" / "sync_lessons.sh"), project_id], check=True)


def write_log(root: Path, rows: list[tuple[str, dict[str, int]]], dry_run: bool) -> Path:
    log_path = root / "logs" / "lesson_when_how_backfill_cmd_2748.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    timestamp = dt.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    with log_path.open("a", encoding="utf-8") as fh:
        fh.write(f"[{timestamp}] dry_run={str(dry_run).lower()}\n")
        for project_id, st in rows:
            total = st["total"]
            fh.write(
                f"{project_id}: total={total} "
                f"when={st['before_when']}/{total}({rate(st['before_when'], total)})"
                f" -> {st['after_when']}/{total}({rate(st['after_when'], total)}); "
                f"how={st['before_how']}/{total}({rate(st['before_how'], total)})"
                f" -> {st['after_how']}/{total}({rate(st['after_how'], total)}); "
                f"changed_lessons={st['changed_lessons']}\n"
            )
    return log_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("projects", nargs="*", default=["dm-signal", "infra"])
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--skip-sync", action="store_true")
    args = parser.parse_args()

    root = script_dir()
    projects = load_projects(root)
    rows: list[tuple[str, dict[str, int]]] = []

    for project_id in args.projects:
        project_path = projects.get(project_id)
        if project_path is None:
            print(f"ERROR: project not found in config/projects.yaml: {project_id}", file=sys.stderr)
            return 1
        lessons_md = project_path / "tasks" / "lessons.md"
        if not lessons_md.exists():
            print(f"ERROR: lessons.md not found: {lessons_md}", file=sys.stderr)
            return 1
        st = backfill_file(lessons_md, args.limit, args.dry_run)
        rows.append((project_id, st))
        if not args.dry_run and not args.skip_sync:
            sync_project(root, project_id)

    log_path = write_log(root, rows, args.dry_run)
    for project_id, st in rows:
        total = st["total"]
        print(
            f"{project_id}: when {st['before_when']}/{total} -> {st['after_when']}/{total}; "
            f"how {st['before_how']}/{total} -> {st['after_how']}/{total}; "
            f"changed_lessons={st['changed_lessons']}"
        )
    print(f"log: {log_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
