#!/usr/bin/env bats
setup(){ TMP=$(mktemp -d); LEDGER="$TMP/ledger.tsv"; GEN="$BATS_TEST_DIRNAME/../../scripts/pytest_speed_task_generator.sh"; export PYTEST_SPEED_STATE_ROOT="$TMP/state"; mkdir -p "$PYTEST_SPEED_STATE_ROOT/queue/tasks" "$PYTEST_SPEED_STATE_ROOT/queue/reports"; }
teardown(){ rm -rf "$TMP"; }
header(){ printf 'timestamp\tnodeid\tduration_sec\toutcome\tfailures\tskips\tcommit\n' >"$LEDGER"; }
row(){ printf '%s\t%s\t%s\t%s\t%s\t%s\tx\n' "$@" >>"$LEDGER"; }
@test "filters fail skip stale malformed and stable sorts" { header; row 1 a::pass 3 passed 0 0; row 1 b::fail 9 failed 1 0; row 1 c::skip 8 passed 0 1; row 1 stale::x 7 passed 0 0; row 2 stale::x 7 failed 1 0; row 1 z::stable 5 passed 0 0; row 1 y::stable 5 passed 0 0; printf '1\tbad::duration\tnope\tpassed\t0\t0\tx\n' >>"$LEDGER"; run bash "$GEN" --ledger "$LEDGER" next; [ "$status" -eq 0 ]; [ "$output" = $'5\ty::stable\n5\tz::stable\n3\ta::pass' ]; }
@test "latest duplicate appears once" { header; row 1 a::x 2 passed 0 0; row 2 a::x 4 passed 0 0; run bash "$GEN" --ledger "$LEDGER" next; [ "$status" -eq 0 ]; [ "$output" = $'4\ta::x' ]; }
@test "active and completed nodeids are excluded" { header; row 1 active::x 4 passed 0 0; row 1 done::x 3 passed 0 0; row 1 free::x 2 passed 0 0; printf 'task:\n  status: in_progress\n  target_nodeid: active::x\n' >"$PYTEST_SPEED_STATE_ROOT/queue/tasks/a.yaml"; printf 'status: completed\ntarget_nodeid: done::x\n' >"$PYTEST_SPEED_STATE_ROOT/queue/reports/d.yaml"; run bash "$GEN" --ledger "$LEDGER" next; [ "$status" -eq 0 ]; [ "$output" = $'2\tfree::x' ]; }
@test "deployment generation excludes until a newer measurement arrives" { header; row 1 active::x 4 passed 0 0; row 1 free::x 2 passed 0 0; printf '1\t0\tactive::x\n' >"$PYTEST_SPEED_STATE_ROOT/queue/pytest_speed_nodeids.tsv"; run bash "$GEN" --ledger "$LEDGER" next; [ "$status" -eq 0 ]; [ "$output" = $'2\tfree::x' ]; row 2 active::x 1 passed 0 0; run bash "$GEN" --ledger "$LEDGER" next; [ "$status" -eq 0 ]; [ "$output" = $'2\tfree::x\n1\tactive::x' ]; }
@test "malformed header fails closed" { printf 'bad\theader\n' >"$LEDGER"; run bash "$GEN" --ledger "$LEDGER" next; [ "$status" -ne 0 ]; [[ "$output" == *malformed* ]]; }
@test "generate emits strict five minute contract" { header; row 1 backend/tests/test_slow.py::test_x 12.5 passed 0 0; run bash "$GEN" --ledger "$LEDGER" generate backend/tests/test_slow.py::test_x "$TMP/task.yaml"; [ "$status" -eq 0 ]; run python3 - "$TMP/task.yaml" <<'PY'
import sys,yaml
t=yaml.safe_load(open(sys.argv[1]))['task']; assert t['project']=='dm-signal' and t['estimated_minutes']==5; assert isinstance(t['target_path'],str); assert t['before_duration_sec']==12.5; assert t['quality_gate']=={'failures':0,'skips':0,'expectation_relaxation':'forbidden'}
PY
 [ "$status" -eq 0 ]; }
@test "deploy cleans temporary YAML and records measured generation" { header; row 1 backend/tests/test_slow.py::test_x 12.5 passed 0 0; mock="$TMP/deploy"; printf '#!/bin/sh\n[ -f "$3" ] || exit 9\nprintf "%%s" "$3" >"%s/seen"\n' "$TMP" >"$mock"; chmod +x "$mock"; run env DEPLOY_TASK="$mock" bash "$GEN" --ledger "$LEDGER" deploy sasuke backend/tests/test_slow.py::test_x; [ "$status" -eq 0 ]; path=$(cat "$TMP/seen"); [ ! -e "$path" ]; grep -q $'1\t0\tbackend/tests/test_slow.py::test_x' "$PYTEST_SPEED_STATE_ROOT/queue/pytest_speed_nodeids.tsv"; }
@test "parallel deploy reserves one nodeid exactly once" { header; row 1 backend/tests/test_slow.py::test_x 12.5 passed 0 0; mock="$TMP/deploy"; printf '#!/bin/sh\nsleep 0.2\nprintf "%%s\\n" "$4" >>"%s/calls"\n' "$TMP" >"$mock"; chmod +x "$mock"; run bash -c 'DEPLOY_TASK="$1" bash "$2" --ledger "$3" deploy sasuke "$4" & a=$!; DEPLOY_TASK="$1" bash "$2" --ledger "$3" deploy hanzo "$4" & b=$!; wait "$a"; ra=$?; wait "$b"; rb=$?; [ $((ra == 0)) -ne $((rb == 0)) ]' _ "$mock" "$GEN" "$LEDGER" backend/tests/test_slow.py::test_x; [ "$status" -eq 0 ]; [ "$(wc -l < "$TMP/calls")" -eq 1 ]; [ "$(wc -l < "$PYTEST_SPEED_STATE_ROOT/queue/pytest_speed_nodeids.tsv")" -eq 1 ]; }
@test "failed deploy rolls reservation back for retry" { header; row 1 backend/tests/test_slow.py::test_x 12.5 passed 0 0; bad="$TMP/bad"; good="$TMP/good"; printf '#!/bin/sh\nexit 7\n' >"$bad"; printf '#!/bin/sh\nexit 0\n' >"$good"; chmod +x "$bad" "$good"; run env DEPLOY_TASK="$bad" bash "$GEN" --ledger "$LEDGER" deploy sasuke backend/tests/test_slow.py::test_x; [ "$status" -eq 7 ]; [ ! -s "$PYTEST_SPEED_STATE_ROOT/queue/pytest_speed_nodeids.tsv" ]; run env DEPLOY_TASK="$good" bash "$GEN" --ledger "$LEDGER" deploy hanzo backend/tests/test_slow.py::test_x; [ "$status" -eq 0 ]; }
@test "unavailable default ledger fails without leaking local project path" { mkdir -p "$TMP/home"; printf 'projects:\n- id: dm-signal\n  path: /runner/nonexistent/DM-signal\n' >"$TMP/projects.yaml"; run env HOME="$TMP/home" XDG_CONFIG_HOME="$TMP/home/config" CAMPAIGN_PROJECTS_CONFIG="$TMP/projects.yaml" bash -c 'cd /tmp && bash "$1" next' _ "$GEN"; [ "$status" -eq 1 ]; [ "$output" = 'BLOCK: default pytest timing ledger unavailable; use --ledger or PYTEST_TIMING_LEDGER' ]; [[ "$output" != *'/runner/nonexistent/DM-signal'* ]]; }
@test "validator accepts generated ledger before cache directory exists" { repo="$BATS_TEST_DIRNAME/../.."; project="$TMP/dm"; mkdir -p "$project/backend/tests"; touch "$project/backend/tests/pytest_duration_ledger_plugin.py"; printf 'projects:\n- id: dm-signal\n  path: %s\n' "$project" >"$TMP/projects.yaml"; run env CAMPAIGN_PROJECTS_CONFIG="$TMP/projects.yaml" python3 "$repo/scripts/validate_campaign_lane_catalog.py" "$repo/config/campaign_lane_catalog.yaml"; [ "$status" -eq 0 ]; [[ "$output" == CATALOG_PASS* ]]; [ ! -e "$project/backend/.pytest_cache" ]; }
@test "validator rejects generated prefix on writer or adapter" { repo="$BATS_TEST_DIRNAME/../.."; cp "$repo/config/campaign_lane_catalog.yaml" "$TMP/bad.yaml"; sed -i 's#writer: scripts/cmd_complete_gate.sh#writer: generated:scripts/cmd_complete_gate.sh#' "$TMP/bad.yaml"; run python3 "$repo/scripts/validate_campaign_lane_catalog.py" "$TMP/bad.yaml"; [ "$status" -ne 0 ]; [[ "$output" == *'ready missing writer'* ]]; }
