#!/usr/bin/env bats
# test_necessity: suppress only stable complete other-command additions to the exact shared operational log.
setup(){ R="$BATS_TEST_TMPDIR/r"; mkdir -p "$R/logs/archive" "$R/scripts/lib"; cp "$BATS_TEST_DIRNAME/../../scripts/lib/report_commit_nonoverlap_filter.sh" "$R/scripts/lib/"; git -C "$R" init -q; git -C "$R" config user.email t@e; git -C "$R" config user.name t; printf '%s\n' '- cmd_id: self' '  review_type: report' '  reviewed_at: t1' '  verdict: LGTM' '- cmd_id: other' '  review_type: report' '  reviewed_at: t2' '  verdict: LGTM' > "$R/logs/gunshi_review_log.yaml"; git -C "$R" add .; git -C "$R" commit -qm base; sed -i 's/LGTM/PASS/g' "$R/logs/gunshi_review_log.yaml"; git -C "$R" add .; git -C "$R" commit -qm self; printf 'parent_cmd: self\ncommit_hash: %s\n' "$(git -C "$R" rev-parse HEAD)" > "$R/report.yaml"; }
f(){ run bash -c 'source "$1/scripts/lib/report_commit_nonoverlap_filter.sh"; filter_report_commit_nonoverlap_uncommitted "$1" "$1/report.yaml" "logs/gunshi_review_log.yaml" 2>/dev/null' _ "$R"; }
@test "other complete entry allowed" { printf '%s\n' '- cmd_id: x' '  review_type: draft' '  reviewed_at: t3' '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml"; f; [ -z "$output" ]; }
@test "allowed auxiliary fields and generations allowed" { sed -i '/cmd_id: other/a\  gate_result: CLEAR\n  gate_synced_at: t4' "$R/logs/gunshi_review_log.yaml"; printf '%s\n' '- cmd_id: x' '  review_type: draft' '  reviewed_at: t3' '  verdict: FAIL' '- cmd_id: y' '  review_type: report' '  reviewed_at: t4' '  verdict: PASS' >> "$R/logs/gunshi_review_log.yaml"; f; [ -z "$output" ]; }
@test "self entry blocked" { printf '%s\n' '- cmd_id: self' '  review_type: draft' '  reviewed_at: t3' '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "mutation blocked" { sed -i '0,/PASS/s//FAIL/' "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "deletion blocked" { sed -i '1,4d' "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "missing identity blocked" { printf '%s\n' '- cmd_id: x' '  review_type: draft' >> "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "unchanged legacy missing identity is grandfathered" { printf '%s\n' '- legacy: unchanged' >> "$R/logs/gunshi_review_log.yaml"; git -C "$R" add .; git -C "$R" commit -qm legacy; sed -i "s/commit_hash:.*/commit_hash: $(git -C "$R" rev-parse HEAD)/" "$R/report.yaml"; printf '%s\n' '- cmd_id: x' '  review_type: draft' '  reviewed_at: t3' '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml"; f; [ -z "$output" ]; }
@test "duplicate identity blocked" { printf '%s\n' '- cmd_id: other' '  review_type: report' '  reviewed_at: t2' '  verdict: PASS' >> "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "unlisted field blocked" { sed -i '/cmd_id: other/a\  unsafe: value' "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "ordinary file blocked" { printf x > "$R/x.yaml"; run bash -c 'source "$1/scripts/lib/report_commit_nonoverlap_filter.sh"; filter_report_commit_nonoverlap_uncommitted "$1" "$1/report.yaml" x.yaml' _ "$R"; [ "$output" = x.yaml ]; }
@test "stable concurrent append allowed" { (sleep .003; printf '%s\n' '- cmd_id: x' '  review_type: draft' '  reviewed_at: tc' '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml") & p=$!; f; wait "$p"; [ -z "$output" ]; }
@test "continuous race blocked" { barrier="$R/writer-ready"; done="$R/filter-done"; (printf '%s\n' '- cmd_id: x1' '  review_type: draft' '  reviewed_at: t1' '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml"; : > "$barrier"; for i in $(seq 2 2000); do printf '%s\n' "- cmd_id: x$i" '  review_type: draft' "  reviewed_at: t$i" '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml"; sleep .002; done; i=2001; while [ ! -f "$done" ]; do printf '%s\n' "- cmd_id: x$i" '  review_type: draft' "  reviewed_at: t$i" '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml"; i=$((i+1)); sleep .002; done) & p=$!; for _ in $(seq 1 200); do [ -f "$barrier" ] && break; sleep .01; done; [ -f "$barrier" ]; f; : > "$done"; wait "$p"; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "canonical archive generation plus append allowed" { head -4 "$R/logs/gunshi_review_log.yaml" > "$R/logs/archive/gunshi_review_log_self_to_self_20260801.yaml"; tail -4 "$R/logs/gunshi_review_log.yaml" > "$R/logs/active"; mv "$R/logs/active" "$R/logs/gunshi_review_log.yaml"; printf '%s\n' '- cmd_id: x' '  review_type: draft' '  reviewed_at: t3' '  verdict: FAIL' >> "$R/logs/gunshi_review_log.yaml"; f; [ -z "$output" ]; }
@test "archive omission blocked" { head -3 "$R/logs/gunshi_review_log.yaml" > "$R/logs/archive/gunshi_review_log_self_to_self_20260801.yaml"; tail -4 "$R/logs/gunshi_review_log.yaml" > "$R/logs/active"; mv "$R/logs/active" "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "archive duplicate blocked" { head -4 "$R/logs/gunshi_review_log.yaml" > "$R/logs/archive/gunshi_review_log_self_to_self_20260801.yaml"; head -4 "$R/logs/gunshi_review_log.yaml" >> "$R/logs/archive/gunshi_review_log_self_to_self_20260801.yaml"; tail -4 "$R/logs/gunshi_review_log.yaml" > "$R/logs/active"; mv "$R/logs/active" "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
@test "archive mutation blocked" { head -4 "$R/logs/gunshi_review_log.yaml" | sed 's/PASS/FAIL/' > "$R/logs/archive/gunshi_review_log_self_to_self_20260801.yaml"; tail -4 "$R/logs/gunshi_review_log.yaml" > "$R/logs/active"; mv "$R/logs/active" "$R/logs/gunshi_review_log.yaml"; f; [ "$output" = logs/gunshi_review_log.yaml ]; }
